title: GDF-MPD Portal
description: World Bank Project - Integration of Mobile Phone Data in National Statistical Systems
theme: jekyll-theme-architect

# This adds a "Download" button to your sidebar automatically
show_downloads: true

# This helps Google find your site (optional, can leave blank)
google_analytics:
