# Book settings
title: GDF-MPD Documentation Portal
author: GDF-MPD
logo: docs/images/Logo - Global Data Facility _Final.png
only_build_toc_files: false

repository:
  url: https://github.com/worldbank/GDF-MPD
  branch: main

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar: false
  extra_navbar: ""
  use_edit_page_button: true
  use_repository_button: true
  use_issues_button: true
  baseurl: https://worldbank.github.io/GDF-MPD
  extra_footer: |
    <div>
     Country borders or names do not necessarily reflect the World Bank Group’s official position. All maps are for illustrative purposes and do not imply the expression of any opinion on the part of the World Bank, concerning the legal status of any country or territory or concerning the delimitation of frontiers or boundaries
    </div>
    <div>
        <b>This project is licensed under the MIT License together with the <a href="https://github.com/worldbank/metadata-editor/blob/main/WB-IGO-RIDER.md">World Bank IGO Rider</a>. The Rider is purely procedural: it reserves all privileges and immunities enjoyed by the World Bank, without adding restrictions to the MIT permissions. Please review both files before using, distributing or contributing.</b>
    </div>
  favicon: docs/images/favicon.ico

#######################################################################################
# Execution settings
execute:
  execute_notebooks: off

#######################################################################################
# Bibliography settings
bibtex_bibfiles:
  - docs/bibliography.bib

#######################################################################################
# Sphinx settings
sphinx:
  config:
    html_show_copyright: false
    html_last_updated_fmt: "%b %d, %Y"
